version: '1.0'

services:
  web:
    build: .
    container_name: flask_app
    command: python run.py
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    depends_on:
      - redis

  worker:
    build: .
    container_name: celery_worker
    command: celery -A app.celery_worker.celery worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
